import cards


def get_Ikoria: Lair of Behemoths_deck():
    decklist = []
    for i in range(12):
        decklist.append(cards.Creature("Adaptive Shimmerer", "Insect", {'Generic': 5}))
        decklist.append(cards.Sorcery("Adventurous Impulse", "", {'Green': 1))
        decklist.append(cards.Creature("Aegis Turtle", "Turtle", {'Blue': 1,))
        decklist.append(cards.Creature("Alert Heedbonder", "Human Scout", {'Green': 1 or 'White': 1, 'Generic': 1, 'Green': 1 or 'White': 1}))
        decklist.append(cards.Creature("Almighty Brushwagg", "Brushwagg", {'Green': 1,))
        decklist.append(cards.Instant("Anticipate", "", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Archipelagore", "Leviathan", {'Generic': 5, 'Blue': 2}))
        decklist.append(cards.Creature("Archipelagore", "Leviathan", {'Generic': 5, 'Blue': 2}))
        decklist.append(cards.Creature("Auspicious Starrix", "Elk Beast", {'Generic': 4, 'Green': 1}))
        decklist.append(cards.Creature("Auspicious Starrix", "Elk Beast", {'Generic': 4, 'Green': 1}))
        decklist.append(cards.Creature("Avian Oddity", "Bird", {'Generic': 3, 'Blue': 1}))
        decklist.append(cards.Instant("Back for More", "", {'Generic': 4, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Instant("Barrier Breach", "", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Enchantment("Bastion of Remembrance", "", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Instant("Blade Banish", "", {'Genric': 3, 'White': 1}))
        decklist.append(cards.Sorcery("Blazing Volley", "", {'Red': 1}))
        decklist.append(cards.Creature("Blisterspit Gremlin", "Gremlin", {'Red': 1}))
        decklist.append(cards.Creature("Blitz Leech", "Leech", {'Generic': 5, 'Black': 1}))
        decklist.append(cards.Instant("Blitz of the Thunder-Raptor", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Instant("Blood Curdle", "" {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Land("Bloodfell Caves", "Land", "", [lambda self: self.owner.add_mana({"Black": 1}), or
                                                                    [lambdoa self: self.owner.add_mana({"Red": 1})]))
        decklist.append(cards.Land("Blossoming Sands", "Land", "", [lambdoa self: self.owner.add_mana({"Green": 1}), or
                                                                           [lambdoa self: self.owner.add_mana({"White": 1})]))
        decklist.append(cards.Land("Bonder's Enclave", "Land", "", [lambda self: self.owner.add_mana({"Diamond": 1}),
        decklist.append(cards.Land("Bonder's Enclave", "Land", "", [lambda self: self.owner.add_mana({"Diamond": 1})                                                                                                                              
        decklist.append(cards.Creature("Boneyard Lurker", "Nightmare Beast", {'Generic': 2, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Creature("Boneyard Lurker", "Nightmate Beast", {'Generic': 2, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Sorcery("Boon of the Wish-Giver", "", {'Generic': 4, 'Blue': 2}))
        decklist.append(cards.Creature("Boot Nipper", "Beast", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Creature("Bristling Boar", "Boar", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Legendary Creature("Brokkos, Apex of Forever", "Nightmare Beast Elemental", {'Generic': 2, 'Black': 1, 'Green': 1, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Brokkos, Apex of Forever", "Nightmare Beast Elemental", {'Generic': 2, 'Black': 1, 'Green': 1, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Brokkos, Apex of Forever", "Nightmare Beast Elemental", {'Generic': 2, 'Black': 1, 'Green': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Bushmeat Poacher", "Human Soldier", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Sorcery("Call of the Death-Dweller", "", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Enchantment("Capture Sphere", "Aura", {'Generic': 3, 'Blue': 1}))
        decklist.append(cards.Sorcery("Cathartic Reunion", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Creature("Cavern Whisperer", "Nightmare", {'Generic': 4, 'Black': 1}))
        decklist.append(cards.Creature("Cavern Whisperer", "Nightmare", {'Generic': 4, 'Black': 1}))
        decklist.append(cards.Instant("Channeled Force", "", {'Generic': 2, 'Blue': 1, 'Red': 1}))
        decklist.append(cards.Sorcery("Charge of the Forever-Beast", "", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Creature("Checkpoint Officer", "Human Soldier", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Legendary Creature("Chevill, Bane of Monsters", "Human Rogue", {'Black': 1, 'Green': 1}))
        decklist.append(cards.Legendary Creature("Chevill, Bane of Monsters", "Human Rogue", {'Black': 1, 'Green': 1}))
        decklist.append(cards.Creature("Chittering Harvester", "Nightmare", {'Generic': 5, 'Black': 1}))
        decklist.append(cards.Creature("Chittering Harvester", "Nightmare", {'Generic': 5, 'Black': 1}))
        decklist.append(cards.Instant("Clash of Titans", "", {'Generic': 3, 'Red': 2}))
        decklist.append(cards.Creature("Cloudpiercer", "Dinosaur", {'Generic': 4, 'Red': 1}))
        decklist.append(cards.Creature("Cloudpiercer", "Dinosaur", {'Generic': 4, 'Red': 1}))
        decklist.append(cards.Enchantment("Colossification", "Aura", {'Generic': 5, 'Green': 2}))
        decklist.append(cards.Enchantment("Colossification", "Aura", {'Generic': 5, 'Green': 2}))
        decklist.append(cards.Enchantment("Colossification", "Aura", {'Generic': 5, 'Green': 2}))
        decklist.append(cards.Instant("Convolute", "", {'Generic': 2, 'Blue': 1}))
        decklist.append(cards.Instant("Coordinated Charge", "", {'Generic': 4, 'White': 1}))
        decklist.append(cards.Instant("Corpse Churn", "", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Creature("Crystacean", "Crab", {'Generic': 3, 'Blue': 1}))
        decklist.append(cards.Artifact Creature("Crystalline Giant", "Giant", {'Generic': 3}))
        decklist.append(cards.Artifact Creature("Crystalline Giant", "Giant", {'Generic': 3}))
        decklist.append(cards.Artifact Creature("Crystalline Giant", "Giant", {'Generic': 3}))
        decklist.append(cards.Creature("Cubwarden", "Cat", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Creature("Cubwarden", "Cat", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Creature("Cunning Nightbonder", "Human Rogue", {'Blue': 1 or 'Black': 1, 'Blue': 1 or 'Black': 1}))
        decklist.append(cards.Instant("Dark Bargain", "", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Creature("Daysquad Marshal", "Human Soldier", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Enchantment("Dead Weight", "Aure", {'Black': 1}))
        decklist.append(cards.Enchantment("Death's Oasis", "", {'White': 1, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Enchantment("Death's Oasis", "", {'White': 1, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Instant("Dire Tactics", "", {'White': 1, 'Black': 1}))
        decklist.append(cards.Creature("Dirge Bat", "Bat", {'Generic': 2, 'Black': 2}))
        decklist.append(cards.Creature("Dirge Bat", "Bat", {'Generic': 2, 'Black': 2}))
        decklist.append(cards.Creature("Dirge Bat", "Bat", {'Generic': 2, 'Black': 2}))
        decklist.append(cards.Land("Dismal Backwater", "Land", "", [lambda self: self.owner.add_mana({"Blue": 1}), or
                                                                     [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Instant("Divine Arrow", "", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Creature("Drannith Healer", "Human Cleric", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Creature("Drannith Magistrate", "Human Wizard", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Creature("Drannith Magistrate", "Human Wizard", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Creature("Drannith Stinger", "Human Wizard", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Creature("Dreamtail Heron", "Elemental Bird", {'Generic': 4, 'Blue': 1}))
        decklist.append(cards.Creature("Dreamtail Heron", "Elemental Bird", {'Generic': 4, 'Blue': 1}))
        decklist.append(cards.Creature("Durable Colibug", "Insect", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Creature("Duskfang Mentor", "Human Cleric", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Instant("Easy Prey", "", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Sorcery("Eerie Ultimatum", "", {'White': 2, 'Black': 3, 'Green': 2}))
        decklist.append(cards.Sorcery("Eerie Ultimatum", "", {'White': 2, 'Black': 3, 'Green': 2}))
        decklist.append(cards.Sorcery("Emergent Ultimatum", "", {'Black': 2, 'Green': 3, 'Blue': 2}))
        decklist.append(cards.Sorcery("Emergent Ultimatum", "", {'Black': 2, 'Green': 3, 'Blue': 2}))
        decklist.append(cards.Enchantment("Escape Protocol", "", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Instant("Essence Scatter", "", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Essence Symbiote", "Beast", {'Generic': 1, 'Green': 1}))
        decklist.append(cards.Creature("Everquill Phoenix", "Phoenix", {'Generic': 2, 'Fire': 2}))
        decklist.append(cards.Creature("Everquill Phoenix", "Phoenix", {'Generic': 2, 'Fire': 2}))
        decklist.append(cards.Creature("Everquill Phoenix", "Phoenix", {'Generic': 2, 'Fire': 2}))
        decklist.append(cards.Land("Evolving Wilds", "Land", "", {'Blue': 0, 'Red': 0, 'Black': 0, 'Green': 0, 'White': 0', 'Colorless': 0}))
        decklist.append(cards.Creature("Excavation Mole", "Mole", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Sorcery("Excavation Event", "", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Sorcery("Excavation Event", "", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Creature("Exuberant Wolfbear", "Wolf Bear", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Creature("Facet", "Human Wizard", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Farfinder", "Fox", {'Generic': 3}))
        decklist.append(cards.Creature("Ferocious Tigorilla", "Cat Ape", {'Generic': 3, 'Red': 1}))
        decklist.append(cards.Creature("Fertilid", "Elemental", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Creature("Fiend Artisan", "Nightmare", {'Black': 1 or Green': 1, 'Black': 1 or Green': 1}))
        decklist.append(cards.Creature("Fiend Artisan", "Nightmare", {'Black': 1 or Green': 1, 'Black': 1 or Green': 1}))
        decklist.append(cards.Instant("Fight as One", "", {'White': 1}))
        decklist.append(cards.Instant("Fire Prophecy", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Instant("Flame Spill", "", {'Generic': 2, 'Red': 1}))
        decklist.append(cards.Creature("Flourishing Fox", "Fox", {'White': 1}))
        decklist.append(cards.Creature("Flourishing Fox", "Fox", {'White': 1}))
        decklist.append(cards.Creature("Flycatcher Giraffid", "Antelope Lizard", {'Generic': 4, 'Green': 1}))
        decklist.append(cards.Enchantment("Foorfall Crater", "Aura", {'Red': 1}))
        decklist.append(cards.Sorcery("Forbidden Friendship", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Sorcery("Forbidden Friendship", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Land("Forest", "Basic Land", "Forest", [lambda self: self.owner.add_mana({"Green": 1})]))
        decklist.append(cards.Land("Forest", "Basic Land", "Forest", [lambda self: self.owner.add_mana({"Green": 1})]))
        decklist.append(cards.Land("Forest", "Basic Land", "Forest", [lambda self: self.owner.add_mana({"Green": 1})]))
        decklist.append(cards.Creature("Frenzied Raptor", "Dinosaur", {'Generic': 2, 'Red': 1}))
        decklist.append(cards.Creature("Frillscare Mentor", "Human Warrior", {'Generic': 2, 'Red': 1}))
        decklist.append(cards.Creature("Frondland Felidar", "Cat Beast", {'Generic': 2, 'Green': 1, 'White': 1}))
        decklist.append(cards.Creature("Frondland Felidar", "Cat Beast", {'Generic': 2, 'Green': 1, 'White': 1}))
        decklist.append(cards.Creature("Frost Lynx", "Elemental Cat", {'Generic': 2, 'Blue': 1}))
        decklist.append(cards.Instant("Frostveil Ambush", "", {'Generic': 3, 'Blue': 2}))
        decklist.append(cards.Instant("Fully Grown", "", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Creature("Garrison Cat", "Cat", {'White': 1}))
        decklist.append(cards.Creature("Gemrazer", "Beast", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Creature("Gemrazer", "Beast", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Creature("Gemrazer", "Beast", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Legendary Creature("General Kudro of Drannith", "Human Soldier", {'Generic': 1, 'White': 1, 'Black': 1}))
        decklist.append(cards.Legendary Creature("General Kudro of Drannith", "Human Soldier", {'Generic': 1, 'White': 1, 'Black': 1}))
        decklist.append(cards.Creature("General's Enforcer", "Human Soldier", {'White': 1, 'Black': 1}))
        decklist.append(cards.Sorcery("Genesis Ultimatum", "", {'Green': 2, 'Blue': 3, 'Red': 2}))
        decklist.append(cards.Sorcery("Genesis Ultimatum", "", {'Green': 2, 'Blue': 3, 'Red': 2}))
        decklist.append(cards.Creature("Glimmerbell", "Elemental Jellyfish", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Gloom Pangolin", "Nightmare Pangolin", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Creature("Glowstone Recluse", "Spider", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Creature("Glowstone Recluse", "Spider", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Sorcery("Go for Blood", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Creature("Greater Sandwurm", "Wurm", {'Generic': 5, 'Green': 2}))
        decklist.append(cards.Creature("Grimdancer", "Nightmare", {'Generic': 1, 'Black': 2}))
        decklist.append(cards.Sorcery("Gust of Wind", "", {'Generic': 3, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Gyruda, Doom of Depths", "Demon Kraken", {'Generic': 4, 'Blue': 1 or 'Black': 1, 'Blue': 1 or 'Black': 1}))
        decklist.append(cards.Legendary Creature("Gyruda, Doom of Depths", "Demon Kraken", {'Generic': 4, 'Blue': 1 or 'Black': 1, 'Blue': 1 or 'Black': 1}))
        decklist.append(cards.Legendary Creature("Gyruda, Doom of Depths", "Demon Kraken", {'Generic': 4, 'Blue': 1 or 'Black': 1, 'Blue': 1 or 'Black': 1}))
        decklist.append(cards.Instant("Hampering Snare", "", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Instant("Heartless Act", "", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Instant("Heartless Act", "", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Instant("Heightened Reflexes", "", {'Red': 1}))
        decklist.append(cards.Creature("Helica Glider", "Nightmare Squirrel", {'Generic': 2, 'White': 1}))
        decklist.append(cards.Creature("Honey Mammoth", "Elephant", {'Generic': 4, 'Green': 2}))
        decklist.append(cards.Creature("Hornbash Mentor", "Human Warrior", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Creature("Humble Naturalist", "Human Druid", {'Generic': 1, 'Green': 1}))
        decklist.append(cards.Creature("Hunted Nightmare", "Nightmare", {'Generic': 1, 'Black': 2}))
        decklist.append(cards.Creature("Hunted Nightmare", "Nightmare", {'Generic': 1, 'Black': 2}))
        decklist.append(cards.Creature("Huntmaster Liger", "Cat", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Creature("Huntmaster Liger", "Cat", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Creature("Huntmaster Liger", "Cat", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Legendary Creature("Illuna, Apex of Wishes", "Beast Elemental Dinosaur", {'Generic': 2, 'Green': 1, 'Blue': 1, 'Red': 1}))
        decklist.append(cards.Legendary Creature("Illuna, Apex of Wishes", "Beast Elemental Dinosaur", {'Generic': 2, 'Green': 1, 'Blue': 1, 'Red': 1}))
        decklist.append(cards.Legendary Creature("Illuna, Apex of Wishes", "Beast Elemental Dinosaur", {'Generic': 2, 'Green': 1, 'Blue': 1, 'Red': 1}))
        decklist.append(cards.Creature("Imposing Vantasaur", "Dinosaur", {'Generic': 5, 'White': 1}))
        decklist.append(cards.Artifact("Indatha Crystal", "", {'Generic': 3}))
        decklist.append(cards.Land("Indatha Triome", "Land", "", [lambda self: self.owner.add_mana({"White": 1}), or
                                                                     [lambda self: self.owner.add_mana({"Black": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Green": 1})]))
        decklist.append(cards.Land("Indatha Triome", "Land", "", [lambda self: self.owner.add_mana({"White": 1}), or
                                                                     [lambda self: self.owner.add_mana({"Black": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Green": 1})]))
        
        decklist.append(cards.Creature("Insatiable Hemophage", "Nightmare", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Creature("Insatiable Hemophage", "Nightmare", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Sorcery("Inspired Ultimatum", "", {'Blue': 2, 'Red': 3, 'White': 2}))
        decklist.append(cards.Sorcery("Inspired Ultimatum", "", {'Blue': 2, 'Red': 3, 'White': 2}))
        decklist.append(cards.Land("Island", "Basic Land", "Island", [lambda self: self.owner.add_mana({"Blue": 1})]))
        decklist.append(cards.Land("Island", "Basic Land", "Island", [lambda self: self.owner.add_mana({"Blue": 1})]))
        decklist.append(cards.Land("Island", "Basic Land", "Island", [lambda self: self.owner.add_mana({"Blue": 1})]))
        decklist.append(cards.Creature("Ivy Elemental", "Elemental", {'Generic': X, 'Green': 1}))
        decklist.append(cards.Legendary Creature("Jegantha, the Wellspring", "Elemental Elk", {'Generic': 4, 'Red': 1 or 'Green': 1}))
        decklist.append(cards.Legendary Creature("Jegantha, the Wellspring", "Elemental Elk", {'Generic': 4, 'Red': 1 or 'Green': 1}))
        decklist.append(cards.Creature("Jubilant Skybonder", "Human Wizard", {'Generic': 1, 'White': 1 or 'Blue': 1, 'White': 1 or 'Blue': 1}))
        decklist.append(cards.Land("Jungle Hollow", "Land", "", [lambda self: self.owner.add_mana({"Black": 1})])) or
                                                                  [lambda self: self.owner.add_mana({"Green": 1})]))
        decklist.append(cards.Legendary Creature("Kaheera, the Orphanguard", "Cat Beast", {'Generic': 1, 'Green': 1 or 'White': 1, 'Green': 1 or 'White': 1))
        decklist.append(cards.Legendary Creature("Kaheera, the Orphanguard", "Cat Beast", {'Generic': 1, 'Green': 1 or 'White': 1, 'Green': 1 or 'White': 1))
        decklist.append(cards.Creature("Keensight Mentor", "Human Cleric", {'Generic': 2, 'White': 1}))
        decklist.append(cards.Instant("Keep Safe", "", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Keruga, the Macrosage", "Dinosaur Hippo", {'Generic': 3, 'Green': 1 or 'Blue': 1, 'Green': 1 or 'Blue': 1))
        decklist.append(cards.Legendary Creature("Keruga, the Macrosage", "Dinosaur Hippo", {'Generic': 3, 'Green': 1 or 'Blue': 1, 'Green': 1 or 'Blue': 1))
        decklist.append(cards.Artifact("Ketria Crystal", "", {'Generic': 3}))
        decklist.append(cards.Land("Ketria Triome", "Land", "", [lambda self: self.owner.add_mana({"Green": 1})])) or
                                                                  [lambda self: self.owner.add_mana({"Blue": 1})])) or
                                                                    [lambda self: self.owner.add_mana({"Red": 1})]))
                                                                    
        decklist.append(cards.Land("Ketria Triome", "Land", "", [lambda self: self.owner.add_mana({"Green": 1})])) or
                                                                  [lambda self: self.owner.add_mana({"Blue": 1})])) or
                                                                    [lambda self: self.owner.add_mana({"Red": 1})]))
        decklist.append(cards.Legendary Creature("Kinnan, Bonder Prodigy", "Human Druid", {'Green': 1, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Kinnan, Bonder Prodigy", "Human Druid", {'Green': 1, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Kogla, the Titan Ape", "Ape", {'Generic': 3, 'Green': 3}))
        decklist.append(cards.Legendary Creature("Kogla, the Titan Ape", "Ape", {'Generic': 3, 'Green': 3}))
        decklist.append(cards.Creature("Labyrinth Raptor", "Nightmare Dinosaur", {'Black': 1, 'Red': 1}))
        decklist.append(cards.Creature("Labyrinth Raptor", "Nightmare Dinosaur", {'Black': 1, 'Red': 1}))
        decklist.append(cards.Creature("Lava Serpent", "Elemental Serpent", {'Generic': 5, 'Red': 1}))
        decklist.append(cards.Creature("Lavabrink Venturer", "Human Soldier", {'Generic': 2, 'White': 1}))
        decklist.append(cards.Creature("Lavabrink Venturer", "Human Soldier", {'Generic': 2, 'White': 1}))
        decklist.append(cards.Sorcery("Lead the Stampede", "", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Instant("Light of Hope", "", {'White': 1}))
        decklist.append(cards.Creature("Lore Drakkis", "Lizard Beast", {'Generic': 1, 'Blue': 1, 'Red': 1}))
        decklist.append(cards.Creature("Lore Drakkis", "Lizard Beast", {'Generic': 1, 'Blue': 1, 'Red': 1}))
        decklist.append(cards.Legendary Planeswalker("Lukka, Coppercoat Outcast", "Lukka", {'Generic': 3, 'Red': 2}))
        decklist.append(cards.Legendary Planeswalker("Lukka, Coppercoat Outcast", "Lukka", {'Generic': 3, 'Red': 2}))
        decklist.append(cards.Creature("Luminous Broodmoth", "Insect", {'Generic': 2, 'White': 2}))
        decklist.append(cards.Creature("Luminous Broodmoth", "Insect", {'Generic': 2, 'White': 2}))
        decklist.append(cards.Creature("Luminous Broodmoth", "Insect", {'Generic': 2, 'White': 2}))
        decklist.append(cards.Creature("Lurking Deadeye", "Human Assassin", {'Generic': 3, 'Black': 1}))
        decklist.append(cards.Legendary Creature("Lurrus of the Dream-Den", "Cat Nightmare", {'Generic': 1, 'White': 1 or 'Black': 1, 'White': 1 or 'Black': 1))
        decklist.append(cards.Legendary Creature("Lurrus of the Dream-Den", "Cat Nightmare", {'Generic': 1, 'White': 1 or 'Black': 1, 'White': 1 or 'Black': 1))
        decklist.append(cards.Legendary Creature("Lutri, the Spellchaser", "Elemental Otter", {'Generic': 1, 'Blue': 1 or 'Red': 1, 'Blue': 1 or 'Red': 1))
        decklist.append(cards.Legendary Creature("Lutri, the Spellchaser", "Elemental Otter", {'Generic': 1, 'Blue': 1 or 'Red': 1, 'Blue': 1 or 'Red': 1))
        decklist.append(cards.Creature("Majestic Auricorn", "Unicorn", {'Generic': 4, 'White': 1}))
        decklist.append(cards.Creature("Majestic Auricorn", "Unicorn", {'Generic': 4, 'White': 1}))
        decklist.append(cards.Creature("Manned Serval", "Cat", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Sorcery("Memory Leak", "", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Sorcery("Migration Path", "", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Sorcery("Migration Path", "", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Creature("Migratory Greathorn", "Beast", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Creature("Migratory Greathorn", "Beast", {'Generic': 3, 'Green': 1}))
        decklist.append(cards.Creature("Momentum Rumbler", "Dinosaur", {'Generic': 3, 'Red': 1}))
        decklist.append(cards.Sorcery("Monstrous Step", "", {'Generic': 4, 'Green': 1}))
        decklist.append(cards.Creature("Mosscoat Goriak", "Beast", {'Generic': 2, 'Green': 1}))
        decklist.append(cards.Land("Mountain", "Basic Land", "Mountain", [lambda self: self.owner.add_mana({"Red": 1})]))
        decklist.append(cards.Land("Mountain", "Basic Land", "Mountain", [lambda self: self.owner.add_mana({"Red": 1})]))
        decklist.append(cards.Land("Mountain", "Basic Land", "Mountain", [lambda self: self.owner.add_mana({"Red": 1})]))
        decklist.append(cards.Sorcery("Mutal Destruction", "", {'Black': 1}))
        decklist.append(cards.Creature("Mysterious Egg", "Egg", {'Generic': 1}))
        decklist.append(cards.Creature("Mysterious Egg", "Egg", {'Generic': 1}))
        decklist.append(cards.Enchantment("Mystic Subdual", "Aura", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Sorcery("Mythos of Brokkos", "", {'Generic': 2, 'Green': 2}))
        decklist.append(cards.Sorcery("Mythos of Brokkos", "", {'Generic': 2, 'Green': 2}))
        decklist.append(cards.Sorcery("Mythos of Illuna", "", {'Generic': 2, 'Blue': 2}))
        decklist.append(cards.Sorcery("Mythos of Illuna", "", {'Generic': 2, 'Blue': 2}))
        decklist.append(cards.Instant("Mythos of Nethroi", "", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Instant("Mythos of Nethroi", "", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Sorcery("Mythos of Snapdax", "", {'Generic': 2, 'White': 2}))
        decklist.append(cards.Sorcery("Mythos of Snapdax", "", {'Generic': 2, 'White': 2}))
        decklist.append(cards.Sorcery("Mythos of Vadrok", "", {'Generic': 2, 'Red': 2}))
        decklist.append(cards.Sorcery("Mythos of Vadrok", "", {'Generic': 2, 'Red': 2}))
        decklist.append(cards.Legendary Planeswalker("Narset of the Ancient Way", "Narset", {'Generic': 1, 'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Legendary Planeswalker("Narset of the Ancient Way", "Narset", {'Generic': 1, 'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Creature("Necropanther", "Cat Nightmare", {'Generic': 1, 'White': 1, 'Black': 1}))
        decklist.append(cards.Creature("Necropanther", "Cat Nightmare", {'Generic': 1, 'White': 1, 'Black': 1}))
        decklist.append(cards.Legendary Creature("Nethroi, Apex of Death", "Cat Nightmare Beast", {'Generic': 2, 'White': 1, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Legendary Creature("Nethroi, Apex of Death", "Cat Nightmare Beast", {'Generic': 2, 'White': 1, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Legendary Creature("Nethroi, Apex of Death", "Cat Nightmare Beast", {'Generic': 2, 'White': 1, 'Black': 1, 'Green': 1}))
        decklist.append(cards.Instant("Neutralize", "", {'Generic': 1, 'Blue': 2}))
        decklist.append(cards.Creature("Nightsqaud Commando", "Human Soldier", {'Generic': 2, 'Black': 1}))
        decklist.append(cards.Legendary Creature("Obosh, the Preypiercer", "Hellion Horror", {'Generic': 3, 'Black': 1 or 'Red': 1, 'Black': 1 or 'Red': 1))
        decklist.append(cards.Legendary Creature("Obosh, the Preypiercer", "Hellion Horror", {'Generic': 3, 'Black': 1 or 'Red': 1, 'Black': 1 or 'Red': 1))
        decklist.append(cards.Sorcery("Of One Mind", "", {'Generic': 2, 'Blue': 1}))
        decklist.append(cards.Enchantment("Offspring's Revenge", "", {'Generic': 2, 'Red': 1, 'White': 1, 'Black': 1}))
        decklist.append(cards.Enchantment("Offspring's Revenge", "", {'Generic': 2, 'Red': 1, 'White': 1, 'Black': 1}))
        decklist.append(cards.Enchantment("Ominous Seas", "", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Enchantment("Pacifism", "Aura", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Creature("Parcelbeast", "Elemental Beast", {'Generic': 2, 'Green': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Parcelbeast", "Elemental Beast", {'Generic': 2, 'Green': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Patagia Tiger", "Cat", {'Generic': 4, 'White': 1}))
        decklist.append(cards.Creature("Perimeter Sergeant", "Human Soldier", {'Generic': 2, 'White': 1}))
        decklist.append(cards.Creature("Phase Dolphin", "Elemental Whale", {'Generic': 2, 'Blue': 1}))
        decklist.append(cards.Land("Plains", "Basic Land", "Plains", [lambda self: self.owner.add_mana({"White": 1})]))
        decklist.append(cards.Land("Plains", "Basic Land", "Plains", [lambda self: self.owner.add_mana({"White": 1})]))
        decklist.append(cards.Land("Plains", "Basic Land", "Plains", [lambda self: self.owner.add_mana({"White": 1})]))
        decklist.append(cards.Instant("Plummet", "", {'Generic': 1, 'Green': 1}))
        decklist.append(cards.Creature("Pollywog Symbiote", "Frog", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Pollywog Symbiote", "Frog", {'Generic': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Porcuparrot", "Bird Beast", {'Generic': 3, 'Red': 1}))
        decklist.append(cards.Creature("Porcuparrot", "Bird Beast", {'Generic': 3, 'Red': 1}))
        decklist.append(cards.Creature("Pouncing Shoreshark", "Shark Beast", {'Generic': 4, 'Blue': 1}))
        decklist.append(cards.Creature("Pouncing Shoreshark", "Shark Beast", {'Generic': 4, 'Blue': 1}))
        decklist.append(cards.Creature("Prickly Marmoset", "Monkey", {'Generic': 2, 'Red': 1}))
        decklist.append(cards.Enchantment("Primal Empathy", "", {'Generic': 1, 'Green': 1, 'Blue': 1}))
        decklist.append(cards.Creature("Proud Wildbonder", "Human Warrior", {'Generic': 2, 'Red': 1 or 'Green': 1, 'Red': 1 or 'Green': 1))
        decklist.append(cards.Creature("Pyroceratops", "Elemental Dinosaur", {'Generic': 3, 'Red': 1}))
        decklist.append(cards.Creature("Quartzwood Crasher", "Dinosaur Beast", {'Generic': 2, 'Red': 2, 'Green': 1}))
        decklist.append(cards.Creature("Quartzwood Crasher", "Dinosaur Beast", {'Generic': 2, 'Red': 2, 'Green': 1}))
        decklist.append(cards.Instant("Raking Claws", "", {'Generic': 1, 'Red': 1}))
        decklist.append(cards.Instant("Ram Through", "", {'Generic': 1, 'Green': 1}))
        decklist.append(cards.Artifact("Raugrin Crystal", "", {'Generic': 3}))
        decklist.append(cards.Land("Raugrin Triome", "Land", "", [lambda self: self.owner.add_mana({"Blue": 1}), or
                                                                     [lambda self: self.owner.add_mana({"Red": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"White": 1})]))
                                                                       
        decklist.append(cards.Land("Raugrin Triome", "Land", "", [lambda self: self.owner.add_mana({"Blue": 1}), or
                                                                     [lambda self: self.owner.add_mana({"Red": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"White": 1})]))
        decklist.append(cards.Enchantment("Reconnaissance Mission", "", {'Generic': 2, 'Blue': 2}))
        decklist.append(cards.Creature("Regal Leosaur", "Dinosaur Cat", {'Red': 1, 'White': 1}))                                                               
        decklist.append(cards.Creature("Regal Leosaur", "Dinosaur Cat", {'Red': 1, 'White': 1}))                                                                
        decklist.append(cards.Enchantment("Reptilian Reflection", "", {'Generic': 2, 'Red': 1}))  
        decklist.append(cards.Legendary Creature("Rielle, the Everwise", "Human Wizard", {'Generic': 1, 'Blue': 1, 'Red': 1}))  
        decklist.append(cards.Legendary Creature("Rielle, the Everwise", "Human Wizard", {'Generic': 1, 'Blue': 1, 'Red': 1})) 
        decklist.append(cards.Creature("Rooting Moloch", "Lizard", {'Generic': 4, 'Red': 1})) 
        decklist.append(cards.Land("Rugged Highlands", "Land", "", [lambda self: self.owner.add_mana({"Red": 1}), or
                                                                     [lambda self: self.owner.add_mana({"Green": 1})]))
        decklist.append(cards.Sorcery("Ruinous Ultimatum", "", {'Red': 2, 'White': 3, 'Black': 2})) 
        decklist.append(cards.Sorcery("Ruinous Ultimatum", "", {'Red': 2, 'White': 3, 'Black': 2})) 
        decklist.append(cards.Sorcery("Rumbling Rockslide", "", {'Generic': 3, 'Red': 1})) 
        decklist.append(cards.Enchantment("Sanctuary Lockdown", "", {'Generic': 2, 'White': 1})) 
        decklist.append(cards.Creature("Sanctuary Smasher", "Rhino Beast", {'Generic': 4, 'Red': 2})) 
        decklist.append(cards.Artifact("Savai Crystal", "", {'Generic': 3})) 
        decklist.append(cards.Creature("Savai Sabertooth", "Cat", {'Generic': 1, 'White': 1})) 
        decklist.append(cards.Creature("Savai Thundername", "Elemental Cat", {'Red': 1, 'White': 1})) 
        decklist.append(cards.Land("Savai Triome", "Land", "", [lambda self: self.owner.add_mana({"Red": 1}), or
                                                                     [lambda self: self.owner.add_mana({"White": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Land("Savai Triome", "Land", "", [lambda self: self.owner.add_mana({"Red": 1}), or
                                                                     [lambda self: self.owner.add_mana({"White": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Land("Scoured Barrens", "Land", "", [lambda self: self.owner.add_mana({"White": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Creature("Sea-Dasher Octopus", "Octopus", {'Generic': 1, 'Blue': 2})) 
        decklist.append(cards.Creature("Sea-Dasher Octopus", "Octopus", {'Generic': 1, 'Blue': 2})) 
        decklist.append(cards.Creature("Serrated Scorpion", "Scorpion", {'Black': 1})) 
        decklist.append(cards.Enchantment("Shark Typhoon", "", {'Generic': 5, 'Blue': 1})) 
        decklist.append(cards.Enchantment("Shark Typhoon", "", {'Generic': 5, 'Blue': 1})) 
        decklist.append(cards.Instant("Shredded Sails", "", {'Generic': 1, 'Red': 1})) 
        decklist.append(cards.Creature("Skull Prophet", "Human Druid", {'Black': 1, 'Green': 1})) 
        decklist.append(cards.Creature("Skycat Sovereign", "Elemental Cat", {'White': 1, 'Blue': 1})) 
        decklist.append(cards.Creature("Skycat Sovereign", "Elemental Cat", {'White': 1, 'Blue': 1})) 
        decklist.append(cards.Artifact("Sleeper Dart", "", {'Generic': 2})) 
        decklist.append(cards.Creature("Slitherwisp", "Elemental Nightmare", {'Blue': 1, 'Black': 2})) 
        decklist.append(cards.Creature("Slitherwisp", "Elemental Nightmare", {'Blue': 1, 'Black': 2})) 
        decklist.append(cards.Legendary Creature("Snapdak, Apex of the Hunt", "Dinosaur Cat Nightmare", {'Generic': 1, 'Red': 1, 'White': 1, 'Black': 1})) 
        decklist.append(cards.Legendary Creature("Snapdak, Apex of the Hunt", "Dinosaur Cat Nightmare", {'Generic': 1, 'Red': 1, 'White': 1, 'Black': 1})) 
        decklist.append(cards.Legendary Creature("Snapdak, Apex of the Hunt", "Dinosaur Cat Nightmare", {'Generic': 1, 'Red': 1, 'White': 1, 'Black': 1})) 
        decklist.append(cards.Creature("Snare Tactician", "Human Soldier", {'Generic': 2, 'White': 1})) 
        decklist.append(cards.Enchantment("Solid Footing", "Aura", {'White': 1})) 
        decklist.append(cards.Enchantment("Song of Creation", "", {'Generic': 1, 'Green': 1, 'Blue': 1, 'Red': 1})) 
        decklist.append(cards.Enchantment("Song of Creation", "", {'Generic': 1, 'Green': 1, 'Blue': 1, 'Red': 1})) 
        decklist.append(cards.Creature("Sonorous Howlbonder", "Human Warrior", {'Generic': 1, 'Black': 1 or 'Red': 1, 'Black': 1 or 'Red': 1))
        decklist.append(cards.Creature("Spelleater Wolverine", "Wolverine", {'Generic': 2, 'Red': 1})) 
        decklist.append(cards.Creature("Splendor Mare", "Elk Unicorn", {'Generic': 2, 'White': 1})) 
        decklist.append(cards.Instant("Spontaneous Flight", "", {'Generic': 2, 'White': 1})) 
        decklist.append(cards.Artifact("Springjaw Trap", "", {'Generic': 1})) 
        decklist.append(cards.Creature("Sprite Dragon", "Faerie Dragon", {'Blue': 1, 'Red': 1})) 
        decklist.append(cards.Creature("Sprite Dragon", "Faerie Dragon", {'Blue': 1, 'Red': 1})) 
        decklist.append(cards.Creature("Sprite Dragon", "Faerie Dragon", {'Blue': 1, 'Red': 1})) 
        decklist.append(cards.Instant("Startling Development", "", {'Generic': 1, 'Blue': 1})) 
        decklist.append(cards.Creature("Stormwild Capridor", "Bird Goat", {'Generic': 2, 'White': 1})) 
        decklist.append(cards.Instant("Sudden Spinnerets", "", {'Green': 1})) 
        decklist.append(cards.Instant("Suffocating Fumes", "", {'Generic': 2, 'Black': 1})) 
        decklist.append(cards.Sorcery("Survivors' Bond", "", {'Generic': 1, 'Green': 1}))
        decklist.append(cards.Sorcery("Swallow Whole", "", {'White': 1})) 
        decklist.append(cards.Land("Swamp", "Basic Land", "Swamp", [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Land("Swamp", "Basic Land", "Swamp", [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Land("Swamp", "Basic Land", "Swamp", [lambda self: self.owner.add_mana({"Black": 1})]))
        decklist.append(cards.Land("Swiftwater Cliffs", "Land", "", [lambda self: self.owner.add_mana({"Blue": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Red": 1})]))
        decklist.append(cards.Sorcery("Tentative Connection", "", {'Generic': 3, 'Red': 1}))
        decklist.append(cards.Legendary Artifact("The Ozolith", "", {'Generic': 1}))
        decklist.append(cards.Legendary Artifact("The Ozolith", "", {'Generic': 1}))
        decklist.append(cards.Creature("Thieving Otter", "Otter", {'Generic': 2, 'Blue': 1}))
        decklist.append(cards.Land("Thornwood Falls", "Land", "", [lambda self: self.owner.add_mana({"Green": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Blue": 1})]))
        decklist.append(cards.Instant("Thwart the Enemy", "", {'Generic': 2, 'Green': 1}))                                                             
        decklist.append(cards.Creature("Titanoth Rex", "Dinosaur Beast", {'Generic': 7, 'Green': 2}))   
        decklist.append(cards.Creature("Titanoth Rex", "Dinosaur Beast", {'Generic': 7, 'Green': 2}))   
        decklist.append(cards.Enchantment("Titans' Nest", "", {'Generic': 1, 'Black': 1, 'Green': 1', 'Blue': 1}))  
        decklist.append(cards.Enchantment("Titans' Nest", "", {'Generic': 1, 'Black': 1, 'Green': 1', 'Blue': 1}))  
        decklist.append(cards.Land("Tranquil Cove", "Land", "", [lambda self: self.owner.add_mana({"White": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Blue": 1})]))
        decklist.append(cards.Creature("Trumpeting Gnarr", "Beast", {'Generic': 1, 'Green': 1, 'Blue': 1}))                                                                 
        decklist.append(cards.Creature("Trumpeting Gnarr", "Beast", {'Generic': 1, 'Green': 1, 'Blue': 1}))  
        decklist.append(cards.Legendary Creature("Umori, the Collector", "Ooze", {'Generic': 2, 'Black': 1 or 'Green': 1, 'Black': 1 or 'Green': 1))
        decklist.append(cards.Legendary Creature("Umori, the Collector", "Ooze", {'Generic': 2, 'Black': 1 or 'Green': 1, 'Black': 1 or 'Green': 1))
        decklist.append(cards.Sorcery("Unbreakable Bond", "", {'Generic': 4, 'Black': 1}))
        decklist.append(cards.Instant("Unexpected Fangs", "", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Instant("Unlikely Aid", "", {'Generic': 1, 'Black': 1}))
        decklist.append(cards.Enchantment("Unpredictable Cyclone", "", {'Generic': 3, 'Red': 2}))
        decklist.append(cards.Enchantment("Unpredictable Cyclone", "", {'Generic': 3, 'Red': 2}))
        decklist.append(cards.Legendary Creature("Vadrok, Apex of Thunder", "Elemental Dinosaur Cat", {'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Legendary Creature("Vadrok, Apex of Thunder", "Elemental Dinosaur Cat", {'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Legendary Creature("Vadrok, Apex of Thunder", "Elemental Dinosaur Cat", {'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Creature("Valiant Rescuer", "Human Soldier", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Legendary Planeswalker("Vivien, Monsters' Advocate", "Vivien", {'Generic': 3, 'Green': 2}))
        decklist.append(cards.Legendary Planeswalker("Vivien, Monsters' Advocate", "Vivien", {'Generic': 3, 'Green': 2}))
        decklist.append(cards.Creature("Void Beckoner", "Nightmare Horror", {'Generic': 6, 'Black': 2}))
        decklist.append(cards.Creature("Void Beckoner", "Nightmare Horror", {'Generic': 6, 'Black': 2}))
        decklist.append(cards.Creature("Void Beckoner", "Nightmare Horror", {'Generic': 6, 'Black': 2}))
        decklist.append(cards.Creature("Voracious Greatshark", "Shark", {'Generic': 3, 'Blue': 2}))
        decklist.append(cards.Creature("Voracious Greatshark", "Shark", {'Generic': 3, 'Blue': 2}))
        decklist.append(cards.Creature("Vulpikeet", "Fox Bird", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Creature("Vulpikeet", "Fox Bird", {'Generic': 3, 'White': 1}))
        decklist.append(cards.Enchantment("Weaponize the Monsters", "", {'Red': 1}))
        decklist.append(cards.Enchantment("Whirlwind of Thought", "", {'Generic': 1, 'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Enchantment("Whirlwind of Thought", "", {'Generic': 1, 'Blue': 1, 'Red': 1, 'White': 1}))
        decklist.append(cards.Creature("Whisper Squad", "Human Soldier", {'Black': 1}))
        decklist.append(cards.Instant("Will of the All-Hunter", "", {'Generic': 1, 'White': 1}))
        decklist.append(cards.Instant("Wilt", "", {'Generic': 1, 'Green': 1}))
        decklist.append(cards.Land("Wind-Scarred Crag", "Land", "", [lambda self: self.owner.add_mana({"Red": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"White": 1})]))
        decklist.append(cards.Creature("Wingfold Pteron", "Dinosaur", {'Generic': 5, 'Blue': 1}))
        decklist.append(cards.Creature("Wingspan Mentor", "Human Wizard", {'Generic': 2, 'Blue': 1}))
        decklist.append(cards.Legendary Creature("Winota, Joiner of Forces", "Human Warrior", {'Generic': 2, 'Red': 1, 'White': 1}))
        decklist.append(cards.Legendary Creature("Winota, Joiner of Forces", "Human Warrior", {'Generic': 2, 'Red': 1, 'White': 1}))
        decklist.append(cards.Legendary Creature("Yidaro, Wandering Monster", "Dinosaur Turtle", {'Generic': 5, 'Red': 2}))
        decklist.append(cards.Legendary Creature("Yidaro, Wandering Monster", "Dinosaur Turtle", {'Generic': 5, 'Red': 2}))
        decklist.append(cards.Legendary Creature("Yidaro, Wandering Monster", "Dinosaur Turtle", {'Generic': 5, 'Red': 2}))
        decklist.append(cards.Legendary Creature("Yorion, Sky Nomad", "Bird Serpent", {'Generic': 3, 'White': 1 or 'Blue': 1, 'White': 1 or 'Blue': 1))
        decklist.append(cards.Legendary Creature("Yorion, Sky Nomad", "Bird Serpent", {'Generic': 3, 'White': 1 or 'Blue': 1, 'White': 1 or 'Blue': 1))
        decklist.append(cards.Artifact("Zagoth Crystal", "", {'Generic': 3}))
        decklist.append(cards.Creature("Zagoth Mamba", "Nightmare Snake", {'Black': 1}))
        decklist.append(cards.Land("Zagoth Triome", "Land", "", [lambda self: self.owner.add_mana({"Black": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Green": 1})])) or
                                                                         [lambda self: self.owner.add_mana({"Blue": 1})])) or
        decklist.append(cards.Land("Zagoth Triome", "Land", "", [lambda self: self.owner.add_mana({"Black": 1})])) or
                                                                       [lambda self: self.owner.add_mana({"Green": 1})])) or
                                                                         [lambda self: self.owner.add_mana({"Blue": 1})]))                                                                 
        decklist.append(cards.Instant("Zenith Flare", "", {'Generic': 2, 'Red': 1, 'White': 1}))
        decklist.append(cards.Legendary Creature("Zilortha, Strength Incarnate", "Dinosaur", {'Generic': 3, 'Red': 1, 'Green': 1}))
        decklist.append(cards.Legendary Creature("Zirda, the Dawnwaker", "Elemental Fox", {'Generic': 1, 'Red': 1 or 'White': 1, 'Red': 1 or 'White': 1 ))
        decklist.append(cards.Legendary Creature("Zirda, the Dawnwaker", "Elemental Fox", {'Generic': 1, 'Red': 1 or 'White': 1, 'Red': 1 or 'White': 1))
        decklist.append(cards.Token Creature - Beast("Beast"))
        decklist.append(cards.Token Creature - Cat("Cat"))
        decklist.append(cards.Token Creature - Cat Bird("Cat Bird"))
        decklist.append(cards.Card("Companion"))
        decklist.append(cards.Token Creature - Dinosaur("Dinosaur"))
        decklist.append(cards.Token Creature - Dinosaur Beast("Dinosaur Beast"))
        decklist.append(cards.Token Artifact("Feather"))
        decklist.append(cards.Token Creature - Human Soldier("Human Soldier"))
        decklist.append(cards.Token Creature - Human Soldier("Human Soldier"))
        decklist.append(cards.Token Creature - Human Soldier("Human Soldier"))
        decklist.append(cards.Token Creature - Kraken("Kraken"))
        decklist.append(cards.Emblem("Narset of the Ancient Way Emblem"))
        decklist.append(cards.Token Creature - Shark("Shark"))
       return decklist


